site_name: CASA Theoretical Knowledge
site_url: https://perthvacc.github.io/TheoryKnowledge/

nav:
  - Home: index.md
  - Aerodromes: 
    - perthad.md
  - Terminal Area:
    - perthtcu.md
  - Enroute:
    - phctr.md
  - Student 1:
    - s1/acd.md
    - s1/smc.md
    - s1/coord.md
  - Student 2:
    - s2/adc.md
    - s2/coord.md
  - Student 3:
    - s3/arrivals.md
    - s3/departures.md
    - s3/coord.md
  - Controller Skills:
    - controllerskills/callsigns.md
    - controllerskills/circuits.md
    - controllerskills/coordination.md
    - controllerskills/handover.md
    - controllerskills/heliops.md
    - controllerskills/rwymanagement.md
    - controllerskills/sequencing.md


theme:
  name: material
  custom_dir: overrides
  logo: assets/images/casalogo.png
  font: 
    text: Maven Pro
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
    - content.tabs.link

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: date

extra_css:
  - stylesheets/admonitions.css
  - stylesheets/navigation.css

markdown_extensions:
  - toc:
      toc_class: custom-toc
  - admonition # Makes things pretty
  - pymdownx.superfences # Nestled code
  - attr_list # Add HTML attributes and CSS classes to Markdown elements
  - pymdownx.tabbed: # Content tabs
      alternate_style: true
  - pymdownx.details # Additional features to admonition
  - pymdownx.caret # Formatting Extension
  - pymdownx.critic # Alternate Formatting Extension
  - pymdownx.mark # Formatting Extension
  - pymdownx.tilde # Formatting Extension
  - pymdownx.keys # Visual keyboard keys extension
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji: # Allows emoji style inline embeds for icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html #enables the use of image figures
  - abbr
  - pymdownx.snippets
  - pymdownx.arithmatex: # Allows the use of math formulas with proper formatting
      generic: true
